import { SiteContent } from './types';

export const CONTENT_VI: SiteContent = {
  meta: {
    documentTitle: "NGÔ PHÚC — Manager / Quản Lí Portfolio & CV",
    description: "CV & Portfolio của Ngô Phúc — Quản lí cửa hàng ALDO GO! ĐL, Quản lý phòng thu SB Studio, Ca trưởng bếp PHỦI STEAK, Ca trưởng VIVA STAR COFFEE.",
    localeLabel: "Tiếng Việt",
  },
  masthead: {
    brandName: "NGÔ PHÚC",
    brandRole: "MANAGER",
    downloadCvLabel: "Tải CV PDF",
    downloadCvUrl: "/NGOPHUC_CV_2026.pdf",
    nav: [
      { id: "overture", label: "Tổng Quan", href: "#overture" },
      { id: "milestones", label: "Kinh Nghiệm", href: "#milestones" },
      { id: "creative-tech", label: "Âm Nhạc & Công Nghệ", href: "#creative-tech" },
      { id: "skills-education", label: "Thế Mạnh & Học Vấn", href: "#skills-education" },
      { id: "contact", label: "Liên Hệ", href: "#contact" },
    ],
    soundToggle: {
      on: "Âm Thanh: Bật",
      off: "Âm Thanh: Tắt",
    },
  },
  chapter00: {
    badge: "HỒ SƠ NĂNG LỰC // 2026",
    name: "NGÔ PHÚC",
    roleTitle: "MANAGER — QUẢN LÍ",
    personalIntro: "Là một người đam mê với nghệ thuật và công nghệ, đặc biệt yêu thích việc quản lí và sắp xếp các quy trình một cách logic và tự động hoá.",
    ctaDownloadCv: "Tải Bản CV PDF (Chính Thức)",
    downloadCvUrl: "/NGOPHUC_CV_2026.pdf",
    ctaContact: "Liên Hệ Trực Tiếp",
    ctaExplore: "Xem Kinh Nghiệm Làm Việc",
  },
  chapter01: {
    index: "01 // KINH NGHIỆM LÀM VIỆC",
    title: "LỊCH SỬ KINH NGHIỆM THỰC CHIẾN",
    subtitle: "Hành trình quản lý, điều phối vận hành và sản xuất từ năm 2019 đến nay.",
    milestones: [
      {
        id: "aldo-go-dalat",
        period: "06/2025 — 07/2026",
        role: "Quản lí cửa hàng",
        company: "ALDO GO! ĐL",
        location: "Đà Lạt, Lâm Đồng",
        type: "retail",
        responsibilities: [
          "Quản lý cửa hàng",
          "Kiểm soát hàng hoá",
          "Quản lý nhân viên",
          "Tăng doanh số bán hàng",
        ],
      },
      {
        id: "phui-steak",
        period: "10/2024 — 06/2025",
        role: "Ca trưởng bếp & Bếp chính",
        company: "PHỦI STEAK",
        location: "Đà Lạt, Lâm Đồng",
        type: "culinary",
        responsibilities: [
          "Đảm bảo số lượng và chất lượng món ăn phục vụ trong ngày",
          "Chuyên trách kỹ thuật áp chảo Steak bò ngoại nhập, chuẩn bị nguyên vật liệu và sơ chế thực phẩm",
          "Làm các món Âu: steak bò, mì Ý, soup, cá hồi, salad,...",
          "Linh hoạt hỗ trợ và điều phối các vị trí khác khi thiếu hụt nhân sự trong ca làm việc",
        ],
        subRoles: [
          {
            period: "02/2025 — 06/2025",
            role: "Bếp chính",
            details: [
              "Chuẩn bị nguyên vật liệu, sơ chế thực phẩm đảm bảo vệ sinh an toàn thực phẩm.",
              "Trực tiếp chế biến các món Âu chuyên sâu: Steak bò ngoại nhập, mì Ý, súp, cá hồi, salad đặc trưng.",
            ],
          },
          {
            period: "10/2024 — 02/2025",
            role: "Ca trưởng bếp",
            details: [
              "Đảm bảo số lượng và chất lượng toàn bộ món ăn phục vụ khách hàng trong ngày.",
              "Chuyên trách kỹ thuật áp chảo Steak bò ngoại nhập chuẩn vị.",
              "Linh hoạt hỗ trợ và điều phối các vị trí thiếu nhân sự trong ca làm việc cao điểm.",
            ],
          },
        ],
      },
      {
        id: "sb-studio",
        period: "03/2023 — 10/2024",
        role: "Quản lý phòng thu",
        company: "CÔNG TY TNHH SB STUDIO",
        location: "Đà Lạt, Lâm Đồng",
        type: "studio",
        responsibilities: [
          "Quản lý tài chính & hoạch định ngân sách",
          "Quản lý truyền thông và chăm sóc khách hàng",
          "Sắp xếp lịch thu âm, quay video clip (MV) đạt chuẩn phát hành",
          "Quản lý nghệ sĩ độc quyền của công ty, kết nối đối tác MCN và truyền thông",
        ],
      },
      {
        id: "viva-star",
        period: "05/2019 — 01/2020",
        role: "Ca trưởng pha chế",
        company: "VIVA STAR COFFEE",
        location: "Đà Lạt, Lâm Đồng",
        type: "fnb",
        responsibilities: [
          "Pha chế cà phê, trà sữa, thức ăn nhanh theo đúng quy chuẩn chất lượng",
          "Sắp xếp ca làm việc và phân công nhiệm vụ cho nhân viên trong ca",
        ],
      },
    ],
  },
  chapter02: {
    index: "02 // ÂM NHẠC & CÔNG NGHỆ",
    title: "NỀN TẢNG SỐ & NGHỆ THUẬT ÂM THANH",
    subtitle: "Khả năng ứng dụng công nghệ, tự động hóa và nghệ thuật sản xuất âm thanh vào thực tiễn.",
    platformName: "HIDDEN MUSIC PLATFORM",
    platformUrl: "https://hiddenmusic.postlain.com",
    platformDescription: "Nền tảng âm nhạc số và không gian phân phối do Ngô Phúc trực tiếp phát triển, kết hợp tư duy công nghệ, thiết kế giao diện tương tác và xử lý âm thanh số.",
    interactionHint: "Tương tác trực tiếp: Rê chuột hoặc chạm vào khung sóng nước bên dưới để trải nghiệm mô phỏng dòng chảy thời gian thực (WebGL Fluid Simulation).",
    listeningRoom: {
      title: "TRÌNH PHÁT ÂM THANH TRỰC TIẾP",
      trackTitle: "POSTLAIN — The Operating Frequency (Original Production)",
      trackMeta: "Sản xuất & Điều hành bởi Ngô Phúc • Hidden Music Ecosystem",
      audioNotice: "Trình phát âm thanh độc quyền kết nối trực tiếp tới nền tảng số. Không tự động phát gây phiền — chủ động kích hoạt trải nghiệm.",
      visitPlatformBtn: "Truy Cập Nền Tảng Hidden Music",
    },
  },
  chapter03: {
    index: "03 // THẾ MẠNH & HỌC VẤN",
    title: "NĂNG LỰC CỐT LÕI & NỀN TẢNG",
    subtitle: "Tổng hợp các kỹ năng chuyên môn, kỹ năng mềm và quá trình học vấn theo CV.",
    skillsTitle: "KỸ NĂNG & THẾ MẠNH",
    skillCategories: [
      {
        title: "Quản Lí Nhân Sự & Vận Hành",
        skills: [
          "Quản lý đội ngũ & phân công ca kíp",
          "Kỹ năng giải quyết vấn đề và xử lý phát sinh",
          "Giao tiếp, kết nối và lãnh đạo tập thể",
          "Hoạt bát, vui vẻ, truyền năng lượng tích cực",
          "Kiểm soát hàng hoá và tối ưu chi phí vận hành",
        ],
      },
      {
        title: "AI & Tự Động Hoá",
        skills: [
          "Sắp xếp và chuẩn hóa logic quy trình công việc",
          "Ứng dụng công cụ AI và tự động hóa tác vụ",
          "Xây dựng hệ thống quản lý dữ liệu số hóa",
          "Tối ưu năng suất và loại bỏ lãng phí thời gian",
        ],
      },
      {
        title: "Ngôn Ngữ & Giao Tiếp",
        skills: [
          "Tiếng Anh giao tiếp và làm việc chuyên nghiệp",
          "Đàm phán đối tác và truyền thông thương hiệu",
          "Chăm sóc khách hàng và tiếp đón khách VIP",
        ],
      },
      {
        title: "Âm Nhạc, Phim Ảnh & Nghệ Thuật",
        skills: [
          "Sản xuất âm nhạc & kỹ thuật phòng thu",
          "Sắp xếp và điều phối quay video clip (MV)",
          "Quản lý quan hệ đối tác mạng lưới MCN",
          "Thẩm mỹ nghệ thuật và thiết kế giao diện web",
        ],
      },
    ],
    educationTitle: "QUÁ TRÌNH HỌC VẤN",
    education: [
      {
        year: "2021",
        school: "Đại Học Văn Lang",
        major: "Quan hệ công chúng (PR)",
        status: "Bảo lưu",
        note: "Nền tảng kiến thức về truyền thông, quan hệ đối tác và xây dựng thương hiệu.",
      },
      {
        year: "2021",
        school: "Cao Đẳng FPT",
        major: "Thiết kế Web",
        status: "Bảo lưu",
        note: "Nền tảng về tư duy giao diện, trải nghiệm người dùng số và công nghệ lập trình web.",
      },
      {
        year: "2020",
        school: "Tốt Nghiệp THPT",
        major: "Trình độ văn hóa 12/12",
        status: "Hoàn thành",
      },
    ],
    hobbiesTitle: "SỞ THÍCH",
    hobbies: ["Âm nhạc", "Đọc sách", "Nghệ thuật", "Chơi thể thao"],
  },
  chapter04: {
    index: "04 // LIÊN HỆ TRỰC TIẾP",
    title: "THÔNG TIN KẾT NỐI",
    subtitle: "Sẵn sàng trao đổi cơ hội nghề nghiệp, hợp tác quản lý và vận hành dự án.",
    hotlineLabel: "HOTLINE TRỰC TIẾP",
    hotlineNumber: "0938-649-420",
    emailLabel: "ĐỊA CHỈ EMAIL",
    emailAddress: "studionopu@gmail.com",
    locationLabel: "ĐỊA CHỈ",
    locationAddress: "Kim Đồng, Phường 6, TP. Đà Lạt, Tỉnh Lâm Đồng",
    downloadCvLabel: "Tải CV PDF Đầy Đủ",
    downloadCvUrl: "/NGOPHUC_CV_2026.pdf",
    copyNotice: "Sao chép",
    copiedNotice: "Đã sao chép!",
    form: {
      title: "GỬI LỜI NHẮN TRỰC TIẾP",
      namePlaceholder: "Họ và tên của bạn",
      emailPlaceholder: "Địa chỉ email liên hệ",
      messagePlaceholder: "Nội dung trao đổi công việc / dự án...",
      submitBtn: "Gửi Lời Nhắn",
      submitting: "Đang gửi...",
      successMessage: "Cảm ơn bạn! Lời nhắn đã được ghi nhận và gửi trực tiếp tới email studionopu@gmail.com.",
      errorMessage: "Không thể gửi thư lúc này. Vui lòng liên hệ trực tiếp qua hotline 0938-649-420.",
    },
  },
  colophon: {
    statement: "Hồ sơ năng lực trực tuyến được xây dựng với hiệu năng cao, chuẩn mực hiện đại và cam kết chất lượng chuẩn xác.",
    techStack: "React 18 • TypeScript • Tailwind CSS • WebGL Shaders • Cloudflare Edge",
    copyright: "© 2026 Ngô Phúc (POSTLAIN). Bản quyền được bảo lưu.",
    backToTop: "Về đầu trang ↑",
  },
};
