import { SiteContent } from './types';

export const CONTENT_EN: SiteContent = {
  meta: {
    documentTitle: "NGO PHUC (POSTLAIN) — Operations & Studio Manager | Da Lat",
    description: "Portfolio & CV of Ngo Phuc (POSTLAIN). Store General Manager at ALDO Flagship, Recording Studio Director at SB Studio, Kitchen Shift Lead at PHUI STEAK & Founder of Hidden Music Platform.",
    localeLabel: "English",
  },
  masthead: {
    monogram: "NGO PHUC // POSTLAIN",
    city: "DA LAT",
    timezone: "GMT+7",
    statusBadge: "AVAILABLE FOR OPERATIONS & MANAGEMENT • 2026",
    nav: [
      { id: "overture", label: "00. OVERVIEW", href: "#overture" },
      { id: "orchestration", label: "01. OPERATIONS", href: "#orchestration" },
      { id: "sonic-space", label: "02. SOUND", href: "#sonic-space" },
      { id: "matrix", label: "03. CAPABILITIES", href: "#matrix" },
      { id: "transmission", label: "04. CONTACT", href: "#transmission" },
    ],
    soundToggle: {
      on: "SOUND: ON",
      off: "SOUND: OFF",
    },
  },
  chapter00: {
    index: "00 // THE OVERTURE",
    thesisTop: "Led by logic.",
    thesisBottom: "Elevated by art.",
    name: "NGO PHUC",
    title: "OPERATIONS & STUDIO MANAGER",
    layerAObservation: "Between the pressure of the retail floor, the coordination of the kitchen line, and the quiet concentration of a night studio in Da Lat: every environment is governed by one underlying discipline — orchestration.",
    recruiterSummary: "Field-tested operations manager with proven leadership across international fashion retail chains, high-volume gastronomy lines, and commercial recording studios. Open for Operations Manager, Store General Manager, and Studio Direction roles.",
    statusLine: "Available for Operations & Store Leadership in Da Lat / Remote • 2026",
    locationAnchor: "Kim Dong St, Ward 6, Da Lat, Lam Dong, Vietnam",
    ctaRecord: "Explore Operational Record",
    ctaContact: "Direct Contact",
    transitionText: "Observing the rhythm of environments I have orchestrated...",
  },
  chapter01: {
    index: "01 // THE RECORD OF ORCHESTRATION",
    title: "OPERATIONAL RECORD & TIMELINE",
    subtitle: "Field-tested leadership track from 2019 to 2026",
    layerAObservation: "Every shift is an orchestral score. Every role, every moment, and every pressure point must align into precise tempo.",
    milestones: [
      {
        id: "aldo-go-dalat",
        period: "06/2025 — 07/2026",
        year: "2025 – 2026",
        role: "Store General Manager",
        company: "ALDO Flagship — GO! Da Lat Mall",
        location: "Da Lat, Lam Dong",
        type: "retail",
        observation: "Before mall doors open, everything is invisible preparation: inventory thresholds, team allocation, and stock readiness.",
        responsibilities: [
          "Directed full-scope operations for the high-end retail flagship at GO! Da Lat mall.",
          "Managed warehouse logistics, inventory thresholds, and stock reallocation with zero margin for error.",
          "Recruited, coached, and inspired a high-performing retail sales team.",
          "Formulated and executed retail strategies to consistently meet and exceed revenue targets.",
        ],
        operationalScope: "Full-scope leadership of international retail flagship, inventory management, and sales team direction.",
      },
      {
        id: "phui-steak-chef",
        period: "02/2025 — 06/2025",
        year: "2025",
        role: "Senior Line Chef",
        company: "PHUI STEAK Gastronomy",
        location: "Da Lat, Lam Dong",
        type: "culinary",
        observation: "Pan-searing is not just about heat; it is about timing calibrated to the exact second.",
        responsibilities: [
          "Prepared premium raw ingredients ensuring strict food safety, cleanliness, and hygiene standards.",
          "Mastered high-end European cuisine: pan-seared imported beef steaks, artisanal pasta, soups, salmon, and signature salads.",
        ],
        operationalScope: "Mastery of European culinary craft, pan-searing precision, and food safety compliance.",
      },
      {
        id: "phui-steak-lead",
        period: "10/2024 — 02/2025",
        year: "2024 – 2025",
        role: "Kitchen Shift Supervisor",
        company: "PHUI STEAK Gastronomy",
        location: "Da Lat, Lam Dong",
        type: "culinary",
        observation: "During peak dinner service, hesitation is failure. A great shift supervisor identifies bottlenecks before they occur.",
        responsibilities: [
          "Guaranteed full daily supply quotas and stringent culinary quality standards.",
          "Specialized in precision pan-searing techniques for gourmet imported beef steaks.",
          "Dynamically coordinated kitchen staff and filled station gaps during high-volume hours.",
        ],
        operationalScope: "High-volume kitchen line supervision, dinner rush coordination, and bottleneck resolution.",
      },
      {
        id: "sb-studio",
        period: "03/2023 — 10/2024",
        year: "2023 – 2024",
        role: "Studio Operations Manager",
        company: "SB Studio Co., Ltd",
        location: "Da Lat, Lam Dong",
        type: "studio",
        observation: "Artists need emotional inspiration, but a recording studio demands strict budgeting, session timing, and release pacing.",
        responsibilities: [
          "Managed studio revenue, operating budget, and strategic commercial service direction.",
          "Directed marketing initiatives, VIP client relations, and strategic corporate partnerships.",
          "Scheduled tracking sessions, vocal recording, and commercial music video productions.",
          "Managed exclusive studio artists, MCN media distribution partners, and entertainment channels.",
        ],
        operationalScope: "Commercial recording studio direction, budget management, artist development, and media production.",
      },
      {
        id: "viva-star",
        period: "05/2019 — 01/2020",
        year: "2019 – 2020",
        role: "Barista Shift Lead",
        company: "VIVA STAR COFFEE",
        location: "Da Lat, Lam Dong",
        type: "fnb",
        observation: "The foundational lesson in management: recipe discipline and shift scheduling precision.",
        responsibilities: [
          "Prepared coffee, specialty teas, and quick-service items adhering strictly to chain standards.",
          "Organized shift rosters and delegated tasks to floor associates to maintain customer service excellence.",
        ],
        operationalScope: "F&B chain shift leadership, standardized quality assurance, and team rostering.",
      },
    ],
    expandLogsLabel: "View Operational Details",
    collapseLogsLabel: "Collapse Details",
    transitionText: "As the physical shift concludes, the studio monitors illuminate...",
  },
  chapter02: {
    index: "02 // THE SONIC SPACE",
    title: "SOUND ARCHITECTURE & CREATIVE VENTURE",
    subtitle: "Digital Music Ecosystem Project",
    ventureName: "HIDDEN MUSIC PLATFORM",
    ventureUrl: "https://hiddenmusic.postlain.com",
    ventureDescription: "A digital audio ecosystem for production, talent direction, and MCN distribution, architected and operated directly by Ngo Phuc (POSTLAIN).",
    layerAObservation: "In the night mist of Da Lat, sound is more than melody. It is the architecture of space, frequency, and emotion.",
    pillars: [
      {
        title: "Audio Engineering & Production",
        desc: "Electronic music composition, multi-track mixing, and spatial acoustic balancing.",
        skills: ["Audio Engineering", "Multi-track Mixing", "Sound Design", "Electronic Production"],
      },
      {
        title: "Copyright Governance & MCN",
        desc: "Managing intellectual property, artist contracts, and multi-channel digital networks.",
        skills: ["Copyright Management", "Artist Development", "MCN Network", "Digital Media"],
      },
      {
        title: "Automated Release Pipelines",
        desc: "Automated release workflows and high-fidelity digital streaming optimization.",
        skills: ["Release Automation", "Cloud Delivery", "Audio Streaming", "Metadata Pacing"],
      },
    ],
    listeningRoom: {
      title: "THE LISTENING ROOM",
      status: "ACTIVE PLATFORM ECOSYSTEM",
      trackTitle: "POSTLAIN — The Operating Frequency (Preview)",
      trackMeta: "Produced by Ngo Phuc • Hidden Music Ecosystem",
      audioNotice: "Integrated audio controller connected to Hidden Music ecosystem. Opt-in user initiated playback only.",
      visitPlatformBtn: "Visit Hidden Music Platform",
    },
    transitionText: "Two contrasting domains, united by one core ability...",
  },
  chapter03: {
    index: "03 // THE OPERATING MATRIX",
    title: "EXECUTIVE CAPABILITIES & FOUNDATION",
    subtitle: "Core Strengths & Academic History",
    layerAObservation: "Discipline is the skeletal frame. Artistic sensibility is the soul. Technology is the lever.",
    capabilitiesTitle: "THREE CORE PILLARS",
    capabilities: [
      {
        title: "Executive Operations Leadership",
        desc: "Observational empathy, accurate staff allocation, inventory governance, and maintaining high morale across teams.",
        skills: ["Store & Kitchen Operations", "Inventory & Budgeting", "Sales Team Coaching", "VIP Client Relations"],
      },
      {
        title: "Workflow Automation & Digital Tooling",
        desc: "Applying logic-driven web systems and modern tools to eliminate administrative friction and streamline operations.",
        skills: ["Workflow Automation", "React / TypeScript / Hono", "Cloudflare Edge Tools", "Process Optimization"],
      },
      {
        title: "Creative Direction & Communication",
        desc: "Audio production, visual brand identity, and fluent bilingual communication in English and Vietnamese.",
        skills: ["Sound Engineering", "MCN Strategy", "Bilingual English", "Editorial Aesthetic"],
      },
    ],
    educationTitle: "ACADEMIC FOUNDATION",
    education: [
      {
        year: "2020",
        school: "High School Graduation",
        major: "General Education (12/12)",
        status: "Completed",
      },
      {
        year: "2021",
        school: "Van Lang University",
        major: "Public Relations (PR)",
        status: "Deferred",
        note: "Foundation in strategic communications, partner relations, and brand positioning.",
      },
      {
        year: "2021",
        school: "FPT Polytechnic College",
        major: "Web Design & Digital Media",
        status: "Deferred",
        note: "Foundation in UI/UX architecture, digital design principles, and modern web code.",
      },
    ],
    transitionText: "Ready to orchestrate new operational value...",
  },
  chapter04: {
    index: "04 // DIRECT TRANSMISSION",
    title: "INITIATE DIALOGUE & DIRECT CONTACT",
    subtitle: "Open for Management Roles & Creative Collaborations",
    layerAObservation: "All lasting professional partnerships begin with a candid, articulate, and direct conversation.",
    hotlineLabel: "DIRECT HOTLINE",
    hotlineNumber: "+84 938-649-420",
    emailLabel: "PRIMARY EMAIL",
    emailAddress: "studionopu@gmail.com",
    locationLabel: "BASE LOCATION",
    locationAddress: "Kim Dong St, Ward 6, Da Lat, Lam Dong, Vietnam",
    copyNotice: "Click to copy",
    copiedNotice: "Copied to clipboard!",
    form: {
      namePlaceholder: "Your Full Name",
      emailPlaceholder: "Your Email Address",
      messagePlaceholder: "Collaboration details or inquiry...",
      submitBtn: "SEND DIRECT INQUIRY",
      submitting: "Dispatching email...",
      successMessage: "Thank you! Your message has been delivered directly to studionopu@gmail.com.",
      errorMessage: "Unable to dispatch email. Please call directly at +84 938-649-420.",
    },
  },
  colophon: {
    statement: "Designed and engineered with an editorial mindset, respecting WCAG accessibility standards and Edge performance.",
    techStack: "React 18 • TypeScript • Vite • Tailwind CSS • Zustand • Hono on Cloudflare Workers",
    coordinates: "11°56'N 108°26'E // DA LAT, VIETNAM",
    copyright: "© 2026 NGO PHUC (POSTLAIN). ALL RIGHTS RESERVED.",
  },
};
