import { SiteContent } from './types';

export const CONTENT_EN: SiteContent = {
  meta: {
    documentTitle: "NGÔ PHÚC — Manager Portfolio & Professional Resume",
    description: "Portfolio & Resume of Ngô Phúc — Store Manager at ALDO GO! DL, Studio Manager at SB Studio, Kitchen Supervisor at PHUI STEAK, Shift Lead at VIVA STAR COFFEE.",
    localeLabel: "English",
  },
  masthead: {
    brandName: "NGÔ PHÚC",
    brandRole: "MANAGER",
    downloadCvLabel: "Download CV PDF",
    downloadCvUrl: "/NGOPHUC_CV_2026.pdf",
    nav: [
      { id: "overture", label: "Overview", href: "#overture" },
      { id: "milestones", label: "Experience", href: "#milestones" },
      { id: "creative-tech", label: "Music & Tech", href: "#creative-tech" },
      { id: "skills-education", label: "Skills & Education", href: "#skills-education" },
      { id: "contact", label: "Contact", href: "#contact" },
    ],
    soundToggle: {
      on: "Sound: On",
      off: "Sound: Off",
    },
  },
  chapter00: {
    badge: "PROFESSIONAL PORTFOLIO // 2026",
    name: "NGÔ PHÚC",
    roleTitle: "MANAGER — OPERATIONS & CREATIVE",
    personalIntro: "Passionate about art and technology, with a dedicated focus on managing and structuring workflows in a logical, automated manner.",
    ctaDownloadCv: "Download Official CV (PDF)",
    downloadCvUrl: "/NGOPHUC_CV_2026.pdf",
    ctaContact: "Direct Contact",
    ctaExplore: "View Work Experience",
  },
  chapter01: {
    index: "01 // WORK EXPERIENCE",
    title: "OPERATIONAL TRACK RECORD",
    subtitle: "Practical management, operations coordination, and production leadership from 2019 to present.",
    milestones: [
      {
        id: "aldo-go-dalat",
        period: "06/2025 — 07/2026",
        role: "Store Manager",
        company: "ALDO GO! DL",
        location: "Da Lat, Lam Dong",
        type: "retail",
        responsibilities: [
          "Overall store operations management",
          "Inventory control & stock management",
          "Staff management, onboarding & coaching",
          "Driving retail sales growth and revenue targets",
        ],
      },
      {
        id: "phui-steak",
        period: "10/2024 — 06/2025",
        role: "Kitchen Shift Supervisor & Line Chef",
        company: "PHỦI STEAK",
        location: "Da Lat, Lam Dong",
        type: "culinary",
        responsibilities: [
          "Ensuring food quantity and highest culinary quality standards daily",
          "Direct execution of imported beef steaks, ingredient preparation and food safety control",
          "Mastering European dishes: steaks, pasta, soups, salmon, signature salads",
          "Agilely supporting and coordinating understaffed stations during peak dinner hours",
        ],
        subRoles: [
          {
            period: "02/2025 — 06/2025",
            role: "Line Chef",
            details: [
              "Fresh ingredient prep, inventory readiness and strict food hygiene compliance.",
              "Directly preparing European specialties: imported steaks, pasta, soup, salmon, signature salads.",
            ],
          },
          {
            period: "10/2024 — 02/2025",
            role: "Kitchen Shift Supervisor",
            details: [
              "Maintaining high culinary quality and speed of service across all stations.",
              "Specialized in high-heat searing techniques for imported beef steaks.",
              "Dynamic cross-station leadership during high-volume rush periods.",
            ],
          },
        ],
      },
      {
        id: "sb-studio",
        period: "03/2023 — 10/2024",
        role: "Recording Studio Manager",
        company: "SB STUDIO CO., LTD",
        location: "Da Lat, Lam Dong",
        type: "studio",
        responsibilities: [
          "Financial oversight and studio budget management",
          "Media relations, marketing direction, and VIP client management",
          "Scheduling recording sessions and music video (MV) productions to commercial standard",
          "Managing exclusive company artists, connecting with MCN partners and entertainment media",
        ],
      },
      {
        id: "viva-star",
        period: "05/2019 — 01/2020",
        role: "Barista Shift Supervisor",
        company: "VIVA STAR COFFEE",
        location: "Da Lat, Lam Dong",
        type: "fnb",
        responsibilities: [
          "Preparing espresso, coffee, milk teas, and quick bites according to franchise standards",
          "Shift scheduling, station assignments, and team supervision",
        ],
      },
    ],
  },
  chapter02: {
    index: "02 // MUSIC & DIGITAL TECHNOLOGY",
    title: "DIGITAL PLATFORM & SOUND CRAFT",
    subtitle: "Applied technical workflows, process automation, and digital audio engineering.",
    platformName: "HIDDEN MUSIC PLATFORM",
    platformUrl: "https://hiddenmusic.postlain.com",
    platformDescription: "A digital audio platform and creator distribution ecosystem developed and maintained by Ngo Phuc, combining modern web engineering, interactive interfaces, and audio signal delivery.",
    interactionHint: "Interactive canvas: Move your mouse or touch the water canvas below to interact with the real-time WebGL Fluid Simulation.",
    listeningRoom: {
      title: "LIVE AUDIO PLAYBACK",
      trackTitle: "POSTLAIN — The Operating Frequency (Original Production)",
      trackMeta: "Produced & Directed by Ngo Phuc • Hidden Music Ecosystem",
      audioNotice: "Direct audio stream connected to the digital platform. Click play to start listening.",
      visitPlatformBtn: "Visit Hidden Music Platform",
    },
  },
  chapter03: {
    index: "03 // STRENGTHS & ACADEMICS",
    title: "CORE CAPABILITIES & BACKGROUND",
    subtitle: "Summary of professional expertise, interpersonal capabilities, and educational background.",
    skillsTitle: "SKILLS & EXPERTISE",
    skillCategories: [
      {
        title: "Personnel & Operations Management",
        skills: [
          "Team leadership & shift scheduling",
          "Problem solving & fast operational resolution",
          "Clear interpersonal communication & team leadership",
          "Energetic, positive attitude, uplifting team morale",
          "Inventory control & cost optimization",
        ],
      },
      {
        title: "AI & Workflow Automation",
        skills: [
          "Process structuring & workflow logic standardization",
          "Applied AI tools & automated business task execution",
          "Digital data management & operational dashboards",
          "Efficiency boosting & friction reduction",
        ],
      },
      {
        title: "Languages & Communication",
        skills: [
          "Professional working proficiency in English",
          "Partner negotiations & brand communications",
          "Customer relationship management & VIP client hospitality",
        ],
      },
      {
        title: "Music, Film & Creative Media",
        skills: [
          "Audio production & studio engineering",
          "Music video (MV) shoot scheduling & coordination",
          "MCN network management & creator relations",
          "Visual design aesthetic & web interface design",
        ],
      },
    ],
    educationTitle: "EDUCATION HISTORY",
    education: [
      {
        year: "2021",
        school: "Van Lang University",
        major: "Public Relations (PR)",
        status: "Deferred",
        note: "Foundational studies in public communications, media relations, and brand building.",
      },
      {
        year: "2021",
        school: "FPT Polytechnic College",
        major: "Web Design",
        status: "Deferred",
        note: "Foundational training in UI/UX architecture, digital design principles, and frontend code.",
      },
      {
        year: "2020",
        school: "High School Graduation",
        major: "General Education 12/12",
        status: "Completed",
      },
    ],
    hobbiesTitle: "INTERESTS & HOBBIES",
    hobbies: ["Music Production", "Reading Books", "Visual Arts", "Sports & Fitness"],
  },
  chapter04: {
    index: "04 // DIRECT CONTACT",
    title: "CONNECT & TRANSMISSION",
    subtitle: "Open to professional opportunities, management roles, and project collaborations.",
    hotlineLabel: "DIRECT HOTLINE",
    hotlineNumber: "0938-649-420",
    emailLabel: "EMAIL ADDRESS",
    emailAddress: "studionopu@gmail.com",
    locationLabel: "LOCATION",
    locationAddress: "Kim Dong, Ward 6, Da Lat City, Lam Dong Province",
    downloadCvLabel: "Download Official CV (PDF)",
    downloadCvUrl: "/NGOPHUC_CV_2026.pdf",
    copyNotice: "Copy",
    copiedNotice: "Copied!",
    form: {
      title: "SEND A DIRECT MESSAGE",
      namePlaceholder: "Your full name",
      emailPlaceholder: "Your contact email",
      messagePlaceholder: "Your message or collaboration inquiry...",
      submitBtn: "Send Message",
      submitting: "Sending...",
      successMessage: "Thank you! Your message has been sent directly to studionopu@gmail.com.",
      errorMessage: "Unable to send at this moment. Please call directly via hotline 0938-649-420.",
    },
  },
  colophon: {
    statement: "Designed and engineered for high responsiveness, modern web standards, and strict factual accuracy.",
    techStack: "React 18 • TypeScript • Tailwind CSS • WebGL Shaders • Cloudflare Edge",
    copyright: "© 2026 Ngo Phuc (POSTLAIN). All rights reserved.",
    backToTop: "Back to top ↑",
  },
};
