import { SiteContent } from './types';

export const CONTENT_VI: SiteContent = {
  meta: {
    documentTitle: "NGÔ PHÚC (POSTLAIN) — Quản Lý Vận Hành & Studio Director | Đà Lạt",
    description: "Portfolio & CV của Ngô Phúc (POSTLAIN). Quản lý cửa hàng ALDO GO! Đà Lạt, quản lý phòng thu SB Studio, ca trưởng bếp PHỦI STEAK & sáng lập nền tảng âm nhạc số Hidden Music.",
    localeLabel: "Tiếng Việt",
  },
  masthead: {
    monogram: "NGÔ PHÚC // POSTLAIN",
    city: "ĐÀ LẠT",
    timezone: "GMT+7",
    statusBadge: "SẴN SÀNG NHẬN VAI TRÒ MỚI • 2026",
    nav: [
      { id: "overture", label: "00. TỔNG QUAN", href: "#overture" },
      { id: "orchestration", label: "01. VẬN HÀNH", href: "#orchestration" },
      { id: "sonic-space", label: "02. ÂM NHẠC", href: "#sonic-space" },
      { id: "matrix", label: "03. THẾ MẠNH", href: "#matrix" },
      { id: "transmission", label: "04. LIÊN HỆ", href: "#transmission" },
    ],
    soundToggle: {
      on: "ÂM THANH: BẬT",
      off: "ÂM THANH: TẮT",
    },
  },
  chapter00: {
    index: "00 // THE OVERTURE",
    thesisTop: "Quản lí bằng logic.",
    thesisBottom: "Thổi hồn bằng nghệ thuật.",
    name: "NGÔ PHÚC",
    title: "OPERATIONS & STUDIO MANAGER",
    layerAObservation: "Giữa áp lực của sàn bán lẻ, nhịp điều phối của gian bếp và sự tĩnh lặng của phòng thu đêm tại Đà Lạt: mọi không gian đều vận hành theo một nguyên lý duy nhất — sự điều phối.",
    recruiterSummary: "Nhà quản lý vận hành giàu kinh nghiệm thực chiến tại chuỗi bán lẻ thời trang quốc tế, bếp ẩm thực tiêu chuẩn cao và phòng thu âm chuyên nghiệp. Sẵn sàng tiếp nhận các vai trò Quản lý Vận hành, Quản lý Cửa hàng hoặc Điều hành Studio.",
    statusLine: "Sẵn sàng nhận vai trò Quản lý & Vận hành tại Đà Lạt / Remote • 2026",
    locationAnchor: "Kim Đồng, Phường 6, Đà Lạt, Lâm Đồng",
    ctaRecord: "Xem Lịch Sử Vận Hành",
    ctaContact: "Liên Hệ Trực Tiếp",
    transitionText: "Nhìn vào nhịp điệu của những nơi tôi đã từng điều phối...",
  },
  chapter01: {
    index: "01 // THE RECORD OF ORCHESTRATION",
    title: "LỊCH SỬ VẬN HÀNH & ĐIỀU PHỐI",
    subtitle: "Hành trình thực chiến từ 2019 đến 2026",
    layerAObservation: "Mỗi ca làm việc là một bản tổng phổ. Từng vị trí, từng thời điểm, từng áp lực đều phải khớp vào một nhịp điệu chính xác.",
    milestones: [
      {
        id: "aldo-go-dalat",
        period: "06/2025 — 07/2026",
        year: "2025 – 2026",
        role: "Quản Lí Cửa Hàng (Store General Manager)",
        company: "ALDO Flagship — TTTM GO! Đà Lạt",
        location: "Đà Lạt, Lâm Đồng",
        type: "retail",
        observation: "Trước khi cửa trung tâm thương mại mở, mọi thứ là sự chuẩn bị vô hình: kho bãi, nhân lực và định mức hàng hóa.",
        responsibilities: [
          "Chịu trách nhiệm quản lý toàn diện vận hành cửa hàng bán lẻ cao cấp tại TTTM GO! Đà Lạt.",
          "Quản trị hệ thống kho bãi, kiểm kê tồn kho và luân chuyển hàng hóa chính xác.",
          "Quản lý, đào tạo và phát triển đội ngũ nhân sự bán hàng chuyên nghiệp.",
          "Xây dựng và thực thi chiến lược thúc đẩy doanh số ngành bán lẻ thời trang cao cấp.",
        ],
        operationalScope: "Quản lý toàn diện cửa hàng thời trang bán lẻ quốc tế, kiểm soát tồn kho và đội ngũ nhân sự.",
      },
      {
        id: "phui-steak-chef",
        period: "02/2025 — 06/2025",
        year: "2025",
        role: "Bếp Chính (Senior Line Chef)",
        company: "PHỦI STEAK Đà Lạt",
        location: "Đà Lạt, Lâm Đồng",
        type: "culinary",
        observation: "Kỹ thuật áp chảo không chỉ là nhiệt độ; đó là sự căn chuẩn thời gian đến từng giây.",
        responsibilities: [
          "Chuẩn bị nguyên vật liệu tươi sống và sơ chế thực phẩm đảm bảo nghiêm ngặt vệ sinh an toàn.",
          "Áp chảo và làm chủ các món Âu chuyên sâu: steak bò ngoại nhập, mì Ý, súp, cá hồi, salad đặc trưng.",
        ],
        operationalScope: "Làm chủ kỹ thuật chế biến ẩm thực Âu cao cấp và kiểm soát an toàn thực phẩm.",
      },
      {
        id: "phui-steak-lead",
        period: "10/2024 — 02/2025",
        year: "2024 – 2025",
        role: "Ca Trưởng Bếp (Kitchen Shift Supervisor)",
        company: "PHỦI STEAK Đà Lạt",
        location: "Đà Lạt, Lâm Đồng",
        type: "culinary",
        observation: "Giờ cao điểm không có chỗ cho sự chần chừ. Một ca trưởng giỏi là người nhìn thấy điểm nghẽn trước khi nó xảy ra.",
        responsibilities: [
          "Đảm bảo số lượng và chất lượng món ăn phục vụ trong ngày đạt tiêu chuẩn cao nhất.",
          "Chuyên trách kỹ thuật áp chảo Steak bò ngoại nhập chuẩn vị Âu.",
          "Linh hoạt hỗ trợ và điều phối các vị trí thiếu hụt nhân sự trong ca cao điểm.",
        ],
        operationalScope: "Giám sát vận hành bếp Âu công suất cao, điều phối luồng món ăn và giải quyết áp lực giờ cao điểm.",
      },
      {
        id: "sb-studio",
        period: "03/2023 — 10/2024",
        year: "2023 – 2024",
        role: "Quản Lý Phòng Thu & Điều Hành (Studio Operations Manager)",
        company: "Công Ty TNHH SB Studio",
        location: "Đà Lạt, Lâm Đồng",
        type: "studio",
        observation: "Nghệ sĩ cần sự thăng hoa, nhưng phòng thu cần kỷ luật về ngân sách, lịch thu và tiến độ phát hành.",
        responsibilities: [
          "Quản lý doanh thu, ngân sách và hoạch định chiến lược kinh doanh dịch vụ âm nhạc.",
          "Định hướng Marketing, chăm sóc khách hàng VIP và đối tác chiến lược.",
          "Sắp xếp lịch thu âm, quay video clip (MV) đạt chuẩn phát hành thương mại.",
          "Quản lý nghệ sĩ độc quyền của công ty, kết nối đối tác mạng lưới MCN và truyền thông giải trí.",
        ],
        operationalScope: "Điều hành toàn diện phòng thu âm thương mại, quản lý ngân sách, nghệ sĩ và sản xuất truyền thông.",
      },
      {
        id: "viva-star",
        period: "05/2019 — 01/2020",
        year: "2019 – 2020",
        role: "Ca Trưởng Pha Chế (Barista Lead)",
        company: "VIVA STAR COFFEE",
        location: "Đà Lạt, Lâm Đồng",
        type: "fnb",
        observation: "Nền tảng đầu tiên của quản trị: tính kỷ luật của công thức và sự chuẩn xác của ca kíp.",
        responsibilities: [
          "Pha chế cà phê, trà sữa và thức ăn nhanh theo tiêu chuẩn công thức chuỗi.",
          "Sắp xếp lịch làm việc theo ca và phân công nhiệm vụ cho nhân viên.",
        ],
        operationalScope: "Quản lý ca vận hành chuỗi F&B và tiêu chuẩn chất lượng dịch vụ.",
      },
    ],
    expandLogsLabel: "Xem Chi Tiết Vận Hành",
    collapseLogsLabel: "Thu Gọn",
    transitionText: "Khi ca làm việc khép lại, cánh cửa phòng thu mở ra...",
  },
  chapter02: {
    index: "02 // THE SONIC SPACE",
    title: "KHÔNG GIAN ÂM THANH & SẢN XUẤT",
    subtitle: "Dự án Nền tảng Âm nhạc Số",
    ventureName: "HIDDEN MUSIC PLATFORM",
    ventureUrl: "https://hiddenmusic.postlain.com",
    ventureDescription: "Hệ sinh thái phân phối, sản xuất âm thanh và định hướng truyền thông cho nghệ sĩ, phát triển và vận hành trực tiếp bởi Ngô Phúc (POSTLAIN).",
    layerAObservation: "Trong sương đêm Đà Lạt, âm thanh không chỉ là giai điệu. Đó là kiến trúc của không gian, tần số và cảm xúc.",
    pillars: [
      {
        title: "Sản Xuất & Kỹ Thuật Âm Thanh",
        desc: "Sản xuất âm nhạc điện tử, thu âm đa kênh và làm chủ kỹ thuật cân chỉnh không gian âm thanh.",
        skills: ["Audio Engineering", "Multi-track Mixing", "Sound Design", "Electronic Production"],
      },
      {
        title: "Quản Trị Bản Quyền & MCN",
        desc: "Quản lý tác quyền âm nhạc, hợp đồng nghệ sĩ và mạng lưới kênh truyền thông số.",
        skills: ["Copyright Management", "Artist Development", "MCN Network", "Digital Media"],
      },
      {
        title: "Tự Động Hóa Phát Hành Số",
        desc: "Quy trình phát hành tự động và tối ưu hóa trải nghiệm âm thanh số trực tuyến.",
        skills: ["Release Automation", "Cloud Delivery", "Audio Streaming", "Metadata Pacing"],
      },
    ],
    listeningRoom: {
      title: "PHÒNG NGHE // THE LISTENING ROOM",
      status: "NỀN TẢNG ĐANG HOẠT ĐỘNG",
      trackTitle: "POSTLAIN — The Operating Frequency (Preview)",
      trackMeta: "Sản xuất bởi Ngô Phúc • Hidden Music Ecosystem",
      audioNotice: "Trình phát âm thanh kết nối trực tiếp tới hệ sinh thái Hidden Music. Không phát tự động — người dùng chủ động trải nghiệm.",
      visitPlatformBtn: "Truy Cập Hidden Music Platform",
    },
    transitionText: "Hai thế giới khác biệt, nhưng chung một năng lực cốt lõi...",
  },
  chapter03: {
    index: "03 // THE OPERATING MATRIX",
    title: "THẾ MẠNH QUẢN TRỊ & NỀN TẢNG",
    subtitle: "Năng lực tổng hợp & Lịch sử đào tạo",
    layerAObservation: "Kỷ luật là khung xương. Sự nhạy cảm nghệ thuật là linh hồn. Công nghệ là đòn bẩy.",
    capabilitiesTitle: "BA TRỤ CỘT NĂNG LỰC",
    capabilities: [
      {
        title: "Quản Trị & Điều Phối Thực Chiến",
        desc: "Khả năng quan sát sắc bén, bố trí nhân sự chính xác, quản trị kho vận và duy trì năng lượng tích cực cho toàn đội ngũ.",
        skills: ["Điều hành cửa hàng & bếp", "Quản lý tồn kho & ngân sách", "Đào tạo nhân sự bán hàng", "Chăm sóc khách hàng VIP"],
      },
      {
        title: "Tự Động Hóa & Công Cụ Số",
        desc: "Ứng dụng công nghệ logic và các công cụ hiện đại để tối ưu hóa quy trình chấm công, kiểm kho và loại bỏ điểm nghẽn thủ công.",
        skills: ["Workflow Automation", "React / TypeScript / Hono", "Cloudflare Edge Tools", "Tối ưu hóa quy trình"],
      },
      {
        title: "Nghệ Thuật & Truyền Thông",
        desc: "Sản xuất âm nhạc, định hướng hình ảnh thương hiệu và khả năng giao tiếp chuyên môn mạch lạc bằng tiếng Anh.",
        skills: ["Sản xuất âm thanh", "Định hướng truyền thông MCN", "Tiếng Anh chuyên ngành", "Thẩm mỹ thiết kế"],
      },
    ],
    educationTitle: "NỀN TẢNG HỌC VẤN",
    education: [
      {
        year: "2020",
        school: "Tốt Nghiệp THPT",
        major: "Trình độ văn hóa 12/12",
        status: "Hoàn thành",
      },
      {
        year: "2021",
        school: "Đại Học Văn Lang",
        major: "Chuyên ngành Quan hệ công chúng (PR)",
        status: "Bảo lưu",
        note: "Nền tảng về truyền thông, quan hệ đối tác và xây dựng thương hiệu.",
      },
      {
        year: "2021",
        school: "Cao Đẳng FPT Polytechnic",
        major: "Chuyên ngành Thiết kế Web & Digital Media",
        status: "Bảo lưu",
        note: "Nền tảng về tư duy giao diện, trải nghiệm người dùng và mã nguồn web.",
      },
    ],
    transitionText: "Sẵn sàng kiến tạo những giá trị vận hành mới...",
  },
  chapter04: {
    index: "04 // DIRECT TRANSMISSION",
    title: "KẾT NỐI & LIÊN HỆ TRỰC TIẾP",
    subtitle: "Mở rộng cơ hội hợp tác nghề nghiệp & dự án",
    layerAObservation: "Mọi sự hợp tác bền vững đều bắt đầu từ một cuộc đối thoại chân thành, rõ ràng và mạch lạc.",
    hotlineLabel: "HOTLINE TRỰC TIẾP",
    hotlineNumber: "0938-649-420",
    emailLabel: "ĐỊA CHỈ EMAIL",
    emailAddress: "studionopu@gmail.com",
    locationLabel: "ĐỊA ĐIỂM HOẠT ĐỘNG",
    locationAddress: "Kim Đồng, Phường 6, Đà Lạt, Lâm Đồng",
    copyNotice: "Nhấp để sao chép",
    copiedNotice: "Đã sao chép vào bộ nhớ tạm!",
    form: {
      namePlaceholder: "Họ và tên của bạn",
      emailPlaceholder: "Địa chỉ email liên hệ",
      messagePlaceholder: "Nội dung trao đổi hợp tác...",
      submitBtn: "GỬI THƯ TRỰC TIẾP",
      submitting: "Đang chuyển thư...",
      successMessage: "Cảm ơn bạn! Lời nhắn đã được gửi thẳng tới studionopu@gmail.com.",
      errorMessage: "Không thể gửi thư lúc này. Vui lòng liên hệ hotline 0938-649-420.",
    },
  },
  colophon: {
    statement: "Thiết kế và phát triển với tư duy biên tập, tôn trọng chuẩn mực tiếp cận WCAG và hiệu năng biên (Edge).",
    techStack: "React 18 • TypeScript • Vite • Tailwind CSS • Zustand • Hono on Cloudflare Workers",
    coordinates: "11°56'N 108°26'E // ĐÀ LẠT, VIỆT NAM",
    copyright: "© 2026 NGÔ PHÚC (POSTLAIN). TẤT CẢ QUYỀN ĐƯỢC BẢO LƯU.",
  },
};
